### ISSUE TITLE
Stylesheets

### ISSUE THREAD

**Issue by caalberts** [caalberts/code-hangout#17]

**Comment by calvintan** [comment]
Outstanding tasks:
- Styling homepage
- Create new gist from navigation
- Fix tab menu for Gist Settings
- Allow either Code Editor or Preview window to be full screen
- Tidy up the 'user is typing...'
- Move delete button to Gist Settings
- Show list from 'Invite a collaborator' in a dropdown - like Min's proj

Enhancements
- Profile photo displayed on dashboard
- Select theme for Code Editor (and Preview?)
