### ISSUE TITLE
Show recently active gists on home page

### ISSUE THREAD

**Issue by caalberts** [caalberts/code-hangout#35]
feature request from @cbas

**Comment by caalberts** [comment]
@calvintan I've listed the recent gists on home page. If you want you can look at the styling :)

**Comment by sebdeckers** [comment]
"recently active" 😅

Hi @caalberts, long time no see. Hope all is well!

**Comment by caalberts** [comment]
Hello @sebdeckers  !! I’m good!! Just doing some spring cleaning. 😂
